export const printerStatus = [
  { status: 0, info: 'None', desc: '未指定状态。' },
  { status: 1, info: 'Paused', desc: '打印队列已暂停。' },
  { status: 2, info: 'Error', desc: '由于错误情况，打印机无法打印。' },
  { status: 4, info: 'PendingDeletion', desc: '打印队列正在删除打印作业。' },
  { status: 8, info: 'PaperJam', desc: '打印机卡纸。' },
  { status: 16, info: 'PaperOut', desc: '打印机中没有或已用完当前打印作业所需的纸张类型。' },
  { status: 32, info: 'ManualFeed', desc: '打印机正在等待用户将打印介质放入手动送纸盒。' },
  { status: 64, info: 'PaperProblem', desc: '打印机中的纸张导致未指定的错误情况。' },
  { status: 128, info: 'Offline', desc: '打印机处于脱机状态。' },
  { status: 256, info: 'IOActive', desc: '打印机正在与打印服务器交换数据。' },
  { status: 512, info: 'Busy', desc: '打印机正忙。' },
  { status: 1024, info: 'Printing', desc: '设备正在打印。' },
  { status: 2048, info: 'OutputBinFull', desc: '打印机的输出纸盒已满。' },
  { status: 4096, info: 'NotAvailable', desc: '状态信息不可用。' },
  { status: 8192, info: 'Waiting', desc: '打印机正在等待打印作业。' },
  { status: 16384, info: 'Processing', desc: '设备正在执行某种工作，如果此设备是集打印机、传真机和扫描仪于一体的多功能设备，则不需要打印。' },
  { status: 32768, info: 'Initializing', desc: '打印机正在初始化。' },
  { status: 65536, info: 'WarmingUp', desc: '打印机正在预热。' },
  { status: 131072, info: 'TonerLow', desc: '打印机中只剩下少量墨粉。' },
  { status: 262144, info: 'NoToner', desc: '打印机墨粉用完。' },
  { status: 524288, info: 'PagePunt', desc: '打印机不能打印当前页。' },
  { status: 1048576, info: 'UserIntervention', desc: '打印机要求通过用户操作来更正错误情况。' },
  { status: 2097152, info: 'OutOfMemory', desc: '打印机无可用内存。' },
  { status: 4194304, info: 'DoorOpen', desc: '打印机上的门已打开。' },
  { status: 8388608, info: 'ServerUnknown', desc: '打印机处于错误状态。' },
  { status: 16777216, info: 'PowerSave', desc: '打印机处于节能模式。' },
];

export const printableStatus = [0, 8192, 16384, 32768, 65536, 1024, 103];
