/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../src/components/app-logo/app-logo.vue')['default']
    BlankView: typeof import('./../src/components/blank-view/blank-view.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb/breadcrumb.vue')['default']
    ElectronicScale: typeof import('./../src/components/electronic-scale/electronic-scale.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    Pagination: typeof import('./../src/components/pagination/pagination.vue')['default']
    PrintDialog: typeof import('./../src/components/print-dialog.vue')['default']
    PrintWeight: typeof import('./../src/components/print-weight.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/svg-icon/svg-icon.vue')['default']
  }
}
