// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
/// <reference path="Electron" />
import type { PPrint } from '../src/../../preload/index';

declare global {
  /**
   * 开发环境
   */
  declare const __DEV__: string;
  // declare const idCard: IdCard;
  interface Window {
    pprint?: PPrint;

  }

}

export {};
